# https://circleci.com/docs/2.0/

version: 2
workflows:
  version: 2
  ci:
    jobs:
      - deploy

jobs:
  deploy:
    machine:
      enabled: true
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: "circleci/classic:201711-01"

    steps:
      - run:
          name: "update system"
          command: |
            sudo apt-get --quiet update

      - "checkout"

      - run:
          name: "deploy"
          command: |
            python3 --version
            packaging/deploy.py

      - store-artifacts:
          path: dist
