# https://circleci.com/docs/2.0/

version: 2
workflows:
  version: 2
  ci:
    jobs:
      - deploy

jobs:
  deploy:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/
      # https://hub.docker.com/r/circleci/python/
      - image: "circleci/python:3"

    steps:
      - "checkout"

      - run:
          name: "deploy"
          command: |
            packaging/deploy.py

      - store-artifacts:
          path: dist
